### PR TITLE
🐛 Fix chunk optimization listeners

### LINKED ISSUE #34: Listeners no longer being properly applied to chunks in v1.1.7
**Type:**
  - [ ] bug
  - [ ] feature
  - [ ] enhancement
  - [x] question

**Environment:**
  - OS:
  - Browser:
  - Library Version:

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
Hey guys, Kudos for taking ownership on this extension.  
Is is working or still WIP? I'm trying to use it with Webpack 5 and it seems to start successfully but it doesn't actually work.  
When I change the `background.js` script the change is not applied.  
Moreover, in the original extension I saw a lot of code getting attached to the `background.js` chunk during the build process and now the only code in chunk is my own.

### PR DESCRIPTION
**Pull request by legitatx**
Fixes listeners not being fired upon "post-process" asset analysis staging in Webpack 5. Closes #34

### CODE REVIEW

**Review by rushilsrivastava — APPROVED** [review]
This looks good!

File: src/webpack/CompilerEventsFacade.ts [hunk 1]
```diff
@@ -15,16 +15,21 @@ export default class CompilerEventsFacade {
...
-        (comp.hooks as any).processAssets.tap(
-          { name: CompilerEventsFacade.extensionName, stage },
-          afterOptimizeChunkAssets,
+        comp.hooks.processAssets.tap(
+          {
+            name: CompilerEventsFacade.extensionName,
+            stage: Compilation.PROCESS_ASSETS_STAGE_ANALYSE,
+          },
+          () => {
+            comp.chunks.forEach((chunk) => {
```
Comment (just-jeb) [inline src/webpack/CompilerEventsFacade.ts:28]: I wonder why is this needed. Isn't `comp.chunks` already a `Set`? According to the Webpack docs it should be...
